import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1783261712415 implements MigrationInterface {
    name = 'Baseline1783261712415'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`username\` varchar(64) NOT NULL, \`nickname\` varchar(64) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`email\` varchar(128) NULL, \`avatar\` text NULL, \`cover\` text NULL, \`bio\` text NOT NULL DEFAULT '', \`gender\` varchar(16) NOT NULL DEFAULT 'secret', \`location\` varchar(64) NOT NULL DEFAULT '', \`verified\` smallint NOT NULL DEFAULT '0', \`verified_note\` varchar(128) NOT NULL DEFAULT '', \`vip\` smallint NOT NULL DEFAULT '0', \`vip_level\` smallint NOT NULL DEFAULT '0', \`invited_by\` int NULL, \`vip_expires\` varchar(32) NULL, \`role\` varchar(16) NOT NULL DEFAULT 'user', \`banned\` smallint NOT NULL DEFAULT '0', \`title\` varchar(64) NOT NULL DEFAULT '', \`avatar_frame\` varchar(64) NOT NULL DEFAULT '', \`points\` int NOT NULL DEFAULT '0', \`experience\` int NOT NULL DEFAULT '0', \`balance\` int NOT NULL DEFAULT '0', \`checkin_streak\` int NOT NULL DEFAULT '0', \`last_checkin\` varchar(16) NULL, \`best_checkin_streak\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, \`updated_at\` varchar(32) NULL, UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`posts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`content\` text NOT NULL DEFAULT '', \`media\` text NOT NULL DEFAULT '[]', \`media_type\` varchar(16) NOT NULL DEFAULT 'text', \`visibility\` varchar(16) NOT NULL DEFAULT 'public', \`password\` varchar(255) NULL, \`price\` int NOT NULL DEFAULT '0', \`location\` varchar(64) NOT NULL DEFAULT '', \`device\` varchar(16) NOT NULL DEFAULT '电脑端', \`topic_id\` int NULL, \`circle_id\` int NULL, \`share_of\` int NULL, \`views\` int NOT NULL DEFAULT '0', \`like_count\` int NOT NULL DEFAULT '0', \`comment_count\` int NOT NULL DEFAULT '0', \`share_count\` int NOT NULL DEFAULT '0', \`edited\` smallint NOT NULL DEFAULT '0', \`pinned\` smallint NOT NULL DEFAULT '0', \`global_pin_until\` varchar(32) NOT NULL DEFAULT '', \`created_at\` varchar(32) NULL, INDEX \`idx_posts_circle\` (\`circle_id\`), INDEX \`idx_posts_vis\` (\`visibility\`), INDEX \`idx_posts_topic\` (\`topic_id\`), INDEX \`idx_posts_created\` (\`created_at\`), INDEX \`idx_posts_user\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`comments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`post_id\` int NULL, \`thread_id\` int NULL, \`article_id\` int NULL, \`user_id\` int NOT NULL, \`parent_id\` int NULL, \`reply_to\` int NULL, \`content\` text NOT NULL, \`like_count\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, INDEX \`idx_comments_thread\` (\`thread_id\`), INDEX \`idx_comments_post\` (\`post_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`follows\` (\`follower_id\` int NOT NULL, \`following_id\` int NOT NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_follows_follower\` (\`follower_id\`), INDEX \`idx_follows_following\` (\`following_id\`), PRIMARY KEY (\`follower_id\`, \`following_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`likes\` (\`user_id\` int NOT NULL, \`target_type\` varchar(16) NOT NULL, \`target_id\` int NOT NULL, \`reaction\` varchar(16) NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_likes_user\` (\`user_id\`), INDEX \`idx_likes_target\` (\`target_type\`, \`target_id\`), PRIMARY KEY (\`user_id\`, \`target_type\`, \`target_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`topics\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(64) NOT NULL, \`description\` text NOT NULL DEFAULT '', \`cover\` text NULL, \`post_count\` int NOT NULL DEFAULT '0', \`hot\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, UNIQUE INDEX \`IDX_1304b1c61016e63f60cd147ce6\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bookmarks\` (\`user_id\` int NOT NULL, \`post_id\` int NOT NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_bookmarks_user\` (\`user_id\`), PRIMARY KEY (\`user_id\`, \`post_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blocks\` (\`blocker_id\` int NOT NULL, \`blocked_id\` int NOT NULL, \`created_at\` varchar(32) NULL, PRIMARY KEY (\`blocker_id\`, \`blocked_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`actor_id\` int NULL, \`type\` varchar(32) NOT NULL, \`target_type\` varchar(16) NULL, \`target_id\` int NULL, \`preview\` text NOT NULL DEFAULT '', \`read\` smallint NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, INDEX \`idx_notifications_user\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchases\` (\`user_id\` int NOT NULL, \`post_id\` int NOT NULL, \`created_at\` varchar(32) NULL, PRIMARY KEY (\`user_id\`, \`post_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`rewards\` (\`id\` int NOT NULL AUTO_INCREMENT, \`from_id\` int NOT NULL, \`to_id\` int NOT NULL, \`post_id\` int NULL, \`amount\` int NOT NULL, \`created_at\` varchar(32) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(128) NOT NULL, \`description\` text NOT NULL DEFAULT '', \`icon\` varchar(32) NOT NULL DEFAULT '🎁', \`category\` varchar(32) NOT NULL DEFAULT 'item', \`payload\` varchar(64) NOT NULL DEFAULT '', \`price\` int NOT NULL, \`stock\` int NOT NULL DEFAULT '-1', \`sold\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`product_id\` int NOT NULL, \`price\` int NOT NULL, \`used\` smallint NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`polls\` (\`id\` int NOT NULL AUTO_INCREMENT, \`post_id\` int NOT NULL, \`multi\` smallint NOT NULL DEFAULT '0', \`deadline\` varchar(32) NULL, \`total_votes\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, INDEX \`idx_polls_post\` (\`post_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`poll_options\` (\`id\` int NOT NULL AUTO_INCREMENT, \`poll_id\` int NOT NULL, \`text\` varchar(80) NOT NULL, \`votes\` int NOT NULL DEFAULT '0', \`idx\` int NOT NULL DEFAULT '0', INDEX \`idx_poll_options_poll\` (\`poll_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`poll_votes\` (\`poll_id\` int NOT NULL, \`option_id\` int NOT NULL, \`user_id\` int NOT NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_poll_votes_lookup\` (\`poll_id\`, \`user_id\`), PRIMARY KEY (\`poll_id\`, \`option_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`circles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(64) NOT NULL, \`slug\` varchar(64) NULL, \`description\` text NOT NULL DEFAULT '', \`category\` varchar(32) NOT NULL DEFAULT '兴趣', \`color\` varchar(32) NOT NULL DEFAULT '', \`icon\` varchar(32) NOT NULL DEFAULT 'circle', \`cover\` text NOT NULL DEFAULT '', \`owner_id\` int NULL, \`member_count\` int NOT NULL DEFAULT '0', \`post_count\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, UNIQUE INDEX \`IDX_420be18c025f652dd7ec506aca\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`circle_members\` (\`circle_id\` int NOT NULL, \`user_id\` int NOT NULL, \`role\` varchar(16) NOT NULL DEFAULT 'member', \`joined_at\` varchar(32) NULL, INDEX \`idx_circle_members_user\` (\`user_id\`), PRIMARY KEY (\`circle_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`sender_id\` int NOT NULL, \`receiver_id\` int NOT NULL, \`content\` text NOT NULL, \`type\` varchar(16) NOT NULL DEFAULT 'text', \`read\` smallint NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, INDEX \`idx_messages_pair\` (\`sender_id\`, \`receiver_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`conversation_settings\` (\`user_id\` int NOT NULL, \`peer_id\` int NOT NULL, \`pinned\` smallint NOT NULL DEFAULT '0', \`muted\` smallint NOT NULL DEFAULT '0', \`updated_at\` varchar(32) NULL, PRIMARY KEY (\`user_id\`, \`peer_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`topic_follows\` (\`user_id\` int NOT NULL, \`topic_id\` int NOT NULL, \`created_at\` varchar(32) NULL, PRIMARY KEY (\`user_id\`, \`topic_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`questions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`title\` varchar(128) NOT NULL, \`body\` text NOT NULL DEFAULT '', \`category\` varchar(32) NOT NULL DEFAULT '综合', \`bounty\` int NOT NULL DEFAULT '0', \`status\` varchar(16) NOT NULL DEFAULT 'open', \`best_answer_id\` int NULL, \`answer_count\` int NOT NULL DEFAULT '0', \`view_count\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, INDEX \`idx_questions_status\` (\`status\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`answers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`question_id\` int NOT NULL, \`user_id\` int NOT NULL, \`content\` text NOT NULL, \`vote_count\` int NOT NULL DEFAULT '0', \`accepted\` smallint NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, INDEX \`idx_answers_question\` (\`question_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`answer_votes\` (\`answer_id\` int NOT NULL, \`user_id\` int NOT NULL, PRIMARY KEY (\`answer_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`flash\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(128) NOT NULL, \`summary\` text NOT NULL DEFAULT '', \`category\` varchar(32) NOT NULL DEFAULT '动态', \`url\` text NOT NULL DEFAULT '', \`pinned\` smallint NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`nav_categories\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(32) NOT NULL, \`icon\` varchar(32) NOT NULL DEFAULT 'compass', \`position\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`nav_links\` (\`id\` int NOT NULL AUTO_INCREMENT, \`category_id\` int NOT NULL, \`title\` varchar(64) NOT NULL, \`url\` varchar(300) NOT NULL, \`description\` text NOT NULL DEFAULT '', \`color\` varchar(32) NOT NULL DEFAULT '', \`clicks\` int NOT NULL DEFAULT '0', \`position\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, INDEX \`idx_nav_links_cat\` (\`category_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_badges\` (\`user_id\` int NOT NULL, \`badge_key\` varchar(32) NOT NULL, \`unlocked_at\` varchar(32) NULL, PRIMARY KEY (\`user_id\`, \`badge_key\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`task_claims\` (\`user_id\` int NOT NULL, \`task_key\` varchar(32) NOT NULL, \`ymd\` varchar(16) NOT NULL, \`claimed_at\` varchar(32) NULL, PRIMARY KEY (\`user_id\`, \`task_key\`, \`ymd\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reports\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reporter_id\` int NOT NULL, \`target_type\` varchar(16) NOT NULL, \`target_id\` int NOT NULL, \`reason\` text NOT NULL DEFAULT '', \`status\` varchar(16) NOT NULL DEFAULT 'open', \`created_at\` varchar(32) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`feedback\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NULL, \`content\` text NOT NULL, \`status\` varchar(16) NOT NULL DEFAULT 'open', \`reply\` text NOT NULL DEFAULT '', \`replied_at\` varchar(32) NULL, \`created_at\` varchar(32) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`boards\` (\`id\` int NOT NULL AUTO_INCREMENT, \`parent_id\` int NULL, \`name\` varchar(64) NOT NULL, \`slug\` varchar(64) NOT NULL, \`description\` text NOT NULL DEFAULT '', \`cover\` text NULL, \`icon\` varchar(32) NULL, \`announcement\` text NOT NULL DEFAULT '', \`is_paid\` smallint NOT NULL DEFAULT '0', \`price\` int NOT NULL DEFAULT '0', \`thread_count\` int NOT NULL DEFAULT '0', \`sort\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, UNIQUE INDEX \`IDX_9a01141982175d5633687bcb47\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`board_follows\` (\`user_id\` int NOT NULL, \`board_id\` int NOT NULL, \`created_at\` varchar(32) NULL, PRIMARY KEY (\`user_id\`, \`board_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`moderators\` (\`board_id\` int NOT NULL, \`user_id\` int NOT NULL, PRIMARY KEY (\`board_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`threads\` (\`id\` int NOT NULL AUTO_INCREMENT, \`board_id\` int NOT NULL, \`user_id\` int NOT NULL, \`title\` varchar(200) NOT NULL, \`content\` text NOT NULL, \`media\` text NOT NULL DEFAULT '[]', \`pinned\` smallint NOT NULL DEFAULT '0', \`elite\` smallint NOT NULL DEFAULT '0', \`locked\` smallint NOT NULL DEFAULT '0', \`views\` int NOT NULL DEFAULT '0', \`like_count\` int NOT NULL DEFAULT '0', \`reply_count\` int NOT NULL DEFAULT '0', \`edited\` smallint NOT NULL DEFAULT '0', \`last_reply_at\` varchar(32) NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_threads_board\` (\`board_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ai_conversations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`title\` varchar(64) NOT NULL DEFAULT '新对话', \`created_at\` varchar(32) NULL, \`updated_at\` varchar(32) NULL, INDEX \`idx_ai_conv_user\` (\`user_id\`, \`updated_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ai_messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`conversation_id\` int NOT NULL, \`role\` varchar(16) NOT NULL, \`content\` text NOT NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_ai_msg_conv\` (\`conversation_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`site_config\` (\`key\` varchar(64) NOT NULL, \`value\` text NOT NULL DEFAULT '', PRIMARY KEY (\`key\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`site_notices\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(128) NOT NULL, \`body\` text NOT NULL DEFAULT '', \`level\` varchar(16) NOT NULL DEFAULT 'info', \`link\` text NOT NULL DEFAULT '', \`link_label\` varchar(64) NOT NULL DEFAULT '', \`active\` smallint NOT NULL DEFAULT '1', \`pinned\` smallint NOT NULL DEFAULT '0', \`created_by\` int NULL, \`created_at\` varchar(32) NULL, \`updated_at\` varchar(32) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`checkin_log\` (\`user_id\` int NOT NULL, \`date\` varchar(16) NOT NULL, \`points\` int NOT NULL DEFAULT '0', \`makeup\` smallint NOT NULL DEFAULT '0', PRIMARY KEY (\`user_id\`, \`date\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`lottery_prizes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(64) NOT NULL, \`type\` varchar(32) NOT NULL, \`value\` varchar(128) NOT NULL DEFAULT '', \`icon\` varchar(32) NOT NULL DEFAULT 'gift', \`color\` varchar(32) NOT NULL DEFAULT '', \`weight\` int NOT NULL DEFAULT '10', \`position\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`lottery_draws\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`prize_id\` int NOT NULL, \`prize_name\` varchar(64) NOT NULL DEFAULT '', \`prize_type\` varchar(32) NOT NULL DEFAULT '', \`created_at\` varchar(32) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`view_history\` (\`user_id\` int NOT NULL, \`target_type\` varchar(16) NOT NULL, \`target_id\` int NOT NULL, \`viewed_at\` varchar(32) NULL, INDEX \`idx_view_history_user\` (\`user_id\`, \`viewed_at\`), PRIMARY KEY (\`user_id\`, \`target_type\`, \`target_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`articles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`title\` varchar(200) NOT NULL, \`summary\` text NOT NULL DEFAULT '', \`cover\` text NOT NULL DEFAULT '', \`content\` mediumtext NOT NULL, \`category\` varchar(32) NOT NULL DEFAULT '综合', \`featured\` smallint NOT NULL DEFAULT '0', \`views\` int NOT NULL DEFAULT '0', \`like_count\` int NOT NULL DEFAULT '0', \`comment_count\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, INDEX \`idx_articles_cat\` (\`category\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`events\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`title\` varchar(200) NOT NULL, \`cover\` text NOT NULL DEFAULT '', \`description\` text NOT NULL DEFAULT '', \`location\` varchar(200) NOT NULL DEFAULT '', \`category\` varchar(32) NOT NULL DEFAULT '聚会', \`start_at\` varchar(32) NOT NULL, \`end_at\` varchar(32) NOT NULL DEFAULT '', \`capacity\` int NOT NULL DEFAULT '0', \`fee\` int NOT NULL DEFAULT '0', \`online\` smallint NOT NULL DEFAULT '0', \`signup_count\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, INDEX \`idx_events_start\` (\`start_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`event_signups\` (\`id\` int NOT NULL AUTO_INCREMENT, \`event_id\` int NOT NULL, \`user_id\` int NOT NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_event_signups\` (\`event_id\`), UNIQUE INDEX \`uq_event_signup\` (\`event_id\`, \`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`thread_subs\` (\`user_id\` int NOT NULL, \`thread_id\` int NOT NULL, \`created_at\` varchar(32) NULL, PRIMARY KEY (\`user_id\`, \`thread_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`red_packets\` (\`id\` int NOT NULL AUTO_INCREMENT, \`post_id\` int NOT NULL, \`user_id\` int NOT NULL, \`total_points\` int NOT NULL, \`total_count\` int NOT NULL, \`remaining_points\` int NOT NULL, \`remaining_count\` int NOT NULL, \`blessing\` varchar(64) NOT NULL DEFAULT '', \`created_at\` varchar(32) NULL, INDEX \`idx_redpacket_post\` (\`post_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`red_packet_grabs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`packet_id\` int NOT NULL, \`user_id\` int NOT NULL, \`amount\` int NOT NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_redpacket_grabs\` (\`packet_id\`), UNIQUE INDEX \`uq_redpacket_grab\` (\`packet_id\`, \`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`board_purchases\` (\`user_id\` int NOT NULL, \`board_id\` int NOT NULL, \`created_at\` varchar(32) NULL, PRIMARY KEY (\`user_id\`, \`board_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admin_audit_log\` (\`id\` int NOT NULL AUTO_INCREMENT, \`admin_id\` int NOT NULL, \`action\` varchar(64) NOT NULL, \`target_type\` varchar(32) NOT NULL DEFAULT '', \`target_id\` int NULL, \`detail\` varchar(300) NOT NULL DEFAULT '', \`created_at\` varchar(32) NULL, INDEX \`idx_audit_created\` (\`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`collections\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`title\` varchar(80) NOT NULL, \`cover\` varchar(500) NOT NULL DEFAULT '', \`description\` varchar(300) NOT NULL DEFAULT '', \`item_count\` int NOT NULL DEFAULT '0', \`created_at\` varchar(32) NULL, \`updated_at\` varchar(32) NULL, INDEX \`idx_collection_user\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`collection_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`collection_id\` int NOT NULL, \`target_type\` varchar(16) NOT NULL, \`target_id\` int NOT NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_collection_item_coll\` (\`collection_id\`), UNIQUE INDEX \`uq_collection_item\` (\`collection_id\`, \`target_type\`, \`target_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`circle_messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`circle_id\` int NOT NULL, \`user_id\` int NOT NULL, \`content\` varchar(1000) NOT NULL, \`created_at\` varchar(32) NULL, INDEX \`idx_circle_msg\` (\`circle_id\`, \`id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_nav_links\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`title\` varchar(40) NOT NULL, \`url\` varchar(300) NOT NULL, \`description\` varchar(120) NOT NULL DEFAULT '', \`created_at\` varchar(32) NULL, INDEX \`idx_user_nav\` (\`user_id\`, \`id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payment_orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`out_trade_no\` varchar(40) NOT NULL, \`user_id\` int NOT NULL, \`gateway\` varchar(16) NOT NULL DEFAULT 'epay', \`channel\` varchar(16) NOT NULL DEFAULT 'alipay', \`amount\` varchar(16) NOT NULL, \`points\` int NOT NULL DEFAULT '0', \`status\` varchar(16) NOT NULL DEFAULT 'pending', \`trade_no\` varchar(64) NOT NULL DEFAULT '', \`created_at\` varchar(32) NULL, \`paid_at\` varchar(32) NULL, INDEX \`idx_pay_user\` (\`user_id\`), UNIQUE INDEX \`idx_pay_out_trade\` (\`out_trade_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`idx_pay_out_trade\` ON \`payment_orders\``);
        await queryRunner.query(`DROP INDEX \`idx_pay_user\` ON \`payment_orders\``);
        await queryRunner.query(`DROP TABLE \`payment_orders\``);
        await queryRunner.query(`DROP INDEX \`idx_user_nav\` ON \`user_nav_links\``);
        await queryRunner.query(`DROP TABLE \`user_nav_links\``);
        await queryRunner.query(`DROP INDEX \`idx_circle_msg\` ON \`circle_messages\``);
        await queryRunner.query(`DROP TABLE \`circle_messages\``);
        await queryRunner.query(`DROP INDEX \`uq_collection_item\` ON \`collection_items\``);
        await queryRunner.query(`DROP INDEX \`idx_collection_item_coll\` ON \`collection_items\``);
        await queryRunner.query(`DROP TABLE \`collection_items\``);
        await queryRunner.query(`DROP INDEX \`idx_collection_user\` ON \`collections\``);
        await queryRunner.query(`DROP TABLE \`collections\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_created\` ON \`admin_audit_log\``);
        await queryRunner.query(`DROP TABLE \`admin_audit_log\``);
        await queryRunner.query(`DROP TABLE \`board_purchases\``);
        await queryRunner.query(`DROP INDEX \`uq_redpacket_grab\` ON \`red_packet_grabs\``);
        await queryRunner.query(`DROP INDEX \`idx_redpacket_grabs\` ON \`red_packet_grabs\``);
        await queryRunner.query(`DROP TABLE \`red_packet_grabs\``);
        await queryRunner.query(`DROP INDEX \`idx_redpacket_post\` ON \`red_packets\``);
        await queryRunner.query(`DROP TABLE \`red_packets\``);
        await queryRunner.query(`DROP TABLE \`thread_subs\``);
        await queryRunner.query(`DROP INDEX \`uq_event_signup\` ON \`event_signups\``);
        await queryRunner.query(`DROP INDEX \`idx_event_signups\` ON \`event_signups\``);
        await queryRunner.query(`DROP TABLE \`event_signups\``);
        await queryRunner.query(`DROP INDEX \`idx_events_start\` ON \`events\``);
        await queryRunner.query(`DROP TABLE \`events\``);
        await queryRunner.query(`DROP INDEX \`idx_articles_cat\` ON \`articles\``);
        await queryRunner.query(`DROP TABLE \`articles\``);
        await queryRunner.query(`DROP INDEX \`idx_view_history_user\` ON \`view_history\``);
        await queryRunner.query(`DROP TABLE \`view_history\``);
        await queryRunner.query(`DROP TABLE \`lottery_draws\``);
        await queryRunner.query(`DROP TABLE \`lottery_prizes\``);
        await queryRunner.query(`DROP TABLE \`checkin_log\``);
        await queryRunner.query(`DROP TABLE \`site_notices\``);
        await queryRunner.query(`DROP TABLE \`site_config\``);
        await queryRunner.query(`DROP INDEX \`idx_ai_msg_conv\` ON \`ai_messages\``);
        await queryRunner.query(`DROP TABLE \`ai_messages\``);
        await queryRunner.query(`DROP INDEX \`idx_ai_conv_user\` ON \`ai_conversations\``);
        await queryRunner.query(`DROP TABLE \`ai_conversations\``);
        await queryRunner.query(`DROP INDEX \`idx_threads_board\` ON \`threads\``);
        await queryRunner.query(`DROP TABLE \`threads\``);
        await queryRunner.query(`DROP TABLE \`moderators\``);
        await queryRunner.query(`DROP TABLE \`board_follows\``);
        await queryRunner.query(`DROP INDEX \`IDX_9a01141982175d5633687bcb47\` ON \`boards\``);
        await queryRunner.query(`DROP TABLE \`boards\``);
        await queryRunner.query(`DROP TABLE \`feedback\``);
        await queryRunner.query(`DROP TABLE \`reports\``);
        await queryRunner.query(`DROP TABLE \`task_claims\``);
        await queryRunner.query(`DROP TABLE \`user_badges\``);
        await queryRunner.query(`DROP INDEX \`idx_nav_links_cat\` ON \`nav_links\``);
        await queryRunner.query(`DROP TABLE \`nav_links\``);
        await queryRunner.query(`DROP TABLE \`nav_categories\``);
        await queryRunner.query(`DROP TABLE \`flash\``);
        await queryRunner.query(`DROP TABLE \`answer_votes\``);
        await queryRunner.query(`DROP INDEX \`idx_answers_question\` ON \`answers\``);
        await queryRunner.query(`DROP TABLE \`answers\``);
        await queryRunner.query(`DROP INDEX \`idx_questions_status\` ON \`questions\``);
        await queryRunner.query(`DROP TABLE \`questions\``);
        await queryRunner.query(`DROP TABLE \`topic_follows\``);
        await queryRunner.query(`DROP TABLE \`conversation_settings\``);
        await queryRunner.query(`DROP INDEX \`idx_messages_pair\` ON \`messages\``);
        await queryRunner.query(`DROP TABLE \`messages\``);
        await queryRunner.query(`DROP INDEX \`idx_circle_members_user\` ON \`circle_members\``);
        await queryRunner.query(`DROP TABLE \`circle_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_420be18c025f652dd7ec506aca\` ON \`circles\``);
        await queryRunner.query(`DROP TABLE \`circles\``);
        await queryRunner.query(`DROP INDEX \`idx_poll_votes_lookup\` ON \`poll_votes\``);
        await queryRunner.query(`DROP TABLE \`poll_votes\``);
        await queryRunner.query(`DROP INDEX \`idx_poll_options_poll\` ON \`poll_options\``);
        await queryRunner.query(`DROP TABLE \`poll_options\``);
        await queryRunner.query(`DROP INDEX \`idx_polls_post\` ON \`polls\``);
        await queryRunner.query(`DROP TABLE \`polls\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP TABLE \`rewards\``);
        await queryRunner.query(`DROP TABLE \`purchases\``);
        await queryRunner.query(`DROP INDEX \`idx_notifications_user\` ON \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`blocks\``);
        await queryRunner.query(`DROP INDEX \`idx_bookmarks_user\` ON \`bookmarks\``);
        await queryRunner.query(`DROP TABLE \`bookmarks\``);
        await queryRunner.query(`DROP INDEX \`IDX_1304b1c61016e63f60cd147ce6\` ON \`topics\``);
        await queryRunner.query(`DROP TABLE \`topics\``);
        await queryRunner.query(`DROP INDEX \`idx_likes_target\` ON \`likes\``);
        await queryRunner.query(`DROP INDEX \`idx_likes_user\` ON \`likes\``);
        await queryRunner.query(`DROP TABLE \`likes\``);
        await queryRunner.query(`DROP INDEX \`idx_follows_following\` ON \`follows\``);
        await queryRunner.query(`DROP INDEX \`idx_follows_follower\` ON \`follows\``);
        await queryRunner.query(`DROP TABLE \`follows\``);
        await queryRunner.query(`DROP INDEX \`idx_comments_post\` ON \`comments\``);
        await queryRunner.query(`DROP INDEX \`idx_comments_thread\` ON \`comments\``);
        await queryRunner.query(`DROP TABLE \`comments\``);
        await queryRunner.query(`DROP INDEX \`idx_posts_user\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`idx_posts_created\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`idx_posts_topic\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`idx_posts_vis\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`idx_posts_circle\` ON \`posts\``);
        await queryRunner.query(`DROP TABLE \`posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
    }

}
